config/routes.rb
Rails.application.routes.draw do

  resources :articles, only: [:create, :new, :show, :edit, :update]
  resources :profiles, only: [:show]

  get 'pages/index'
  get 'pages/about'

  resources :tags, only: [:index, :show]

  devise_for :users, :controllers => {:registrations => "users/registrations"}

  devise_scope :user do
    get "signin" , to: "devise/sessions#new"
    get "signup" , to: "devise/registrations#new"
    get "signout", to: "devise/sessions#destroy"
  end

  root 'pages#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user

  validates :title, presence: true, length: { maximum: 50 }
  validates :content, presence: true, length: { maximum: 5000 }
  validates :picture, presence: true

  mount_uploader :picture, PictureUploader

  acts_as_taggable
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :authenticate_user!, except: [:show]
  before_action :owner, only: [:edit, :update]

  def show
    @article = Article.find(params[:id])
  end

  def new
  	@article = current_user.articles.build
  end

  def create
  	@article = current_user.articles.build(article_params)
    if @article.save
      flash[:success] = "Article Posted Successfully"
      redirect_to root_path
    else
      flash.now[:danger] = "Something went Wrong while saving the Article"
      render "new"
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if(@article.update_attributes(article_params))
      flash[:success] = "article successfully updated"
      redirect_to article_path(@article)
    else
      render :edit
    end

  end

  private

  	def article_params
  		params.require(:article).permit(:title, :content, :picture, :tag_list)
  	end

    def owner
      @article = Article.find(params[:id])
      unless current_user == @article.user
        redirect_to root_path
      end 
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper

	def article_owner?(user)
		current_user == user ? true : false
	end
end

app/views/articles/_article.html.erb
<div class="col-sm-4 article">
	<%= link_to image_tag(article.picture.thumb), article_path(article) %>
	<h1><%= article.title %></h1>
	<p><%= truncate(article.content, length: 100)  %></p>

	<ul>
		<li>by: <%=  link_to article.user.name, profile_path(article.user) %> | </li>
		<li><a href="http://localhost:3000/articles/<%= article.id %>#disqus_thread">Link</a></li>
		<li>
			<% if article_owner?(article.user) %>
			 | <%= link_to "Edit", edit_article_path(article)  %>
			<% end %>
		</li>
	</ul>
</div>

app/views/articles/_disqus.html.erb
<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES * * */
    var disqus_shortname = 'codebloggers';
    var disqus_identifier = '<%= @article.id %>';
    var disqus_title = '<%= @article.title %>';
    var disqus_url = '<%= url_for([@article, {only_path: false}]) %>';
    
    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/articles/edit.html.erb
<div class="col-md-12">
	<%= form_for(@article) do |f| %>

		<%= render "shared/errors", object: f.object %>

		<div class="form-group">
			<%= f.text_field :title, placeholder: "Title", class: "form-control"  %>
		</div>
		
		<div class="form-group">
			<%= f.text_area :content, placeholder: "Content", class: "form-control" %>
		</div>

		<div class="form-group">
			<%= f.text_area :tag_list, placeholder: "Enter tags sperated by ,", class: "form-control" %>
		</div>

		<div class="form-group">
			<%= f.file_field :picture, class: "form-control" %>
			<%= f.hidden_field :picture_cache %>
		</div>

		<%= f.submit "Save", class: "btn btn-primary" %>
	<% end %>
</div>

app/views/articles/new.html.erb
<div class="col-md-12">
	<%= form_for(@article) do |f| %>

		<%= render "shared/errors", object: f.object %>

		<div class="form-group">
			<%= f.text_field :title, placeholder: "Title", class: "form-control"  %>
		</div>
		
		<div class="form-group">
			<%= f.text_area :content, placeholder: "Content", class: "form-control" %>
		</div>

		<div class="form-group">
			<%= f.text_area :tag_list, placeholder: "Enter tags sperated by ,", class: "form-control" %>
		</div>

		<div class="form-group">
			<%= f.file_field :picture, class: "form-control" %>
			<%= f.hidden_field :picture_cache %>
		</div>

		<%= f.submit "Save", class: "btn btn-primary" %>
	<% end %>
</div>

app/views/articles/show.html.erb
<div class="col-md-12">
	<%= link_to image_tag(@article.picture), article_path(@article) %>
	<p>Posted by: <%=  link_to @article.user.name, profile_path(@article.user) %>, 
	Posted <%= time_ago_in_words(@article.created_at) %> ago </p>

	<p><%= raw @article.tag_list.map { |tag|  link_to tag, tag_path(tag) }.join(', ')  %></p>

	<h1><%= @article.title %></h1>

	<p><%= @article.content %></p>

	<%= render "disqus" %>
</div>