config/routes.rb
Rails.application.routes.draw do

  resources :articles, only: [:create, :new, :show, :edit, :update]
  resources :profiles, only: [:show]

  get 'pages/index'
  get 'pages/about'

  resources :tags, only: [:index, :show]

  devise_for :users, :controllers => {:registrations => "users/registrations"}

  devise_scope :user do
    get "signin" , to: "devise/sessions#new"
    get "signup" , to: "devise/registrations#new"
    get "signout", to: "devise/sessions#destroy"
  end

  root 'pages#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
	<% unless key.include?("timedout") %>
		<div class="<%= bootstrap_class_new_name(key) %>">
			<p ><%= value %></p>
		</div>
	<% end %>
<% end %>

app/views/layouts/_header.html.erb
<div class="col-md-3 main-sidebar">
	<aside>
		<h2 class="logo"> <%= link_to "CODE BLOGGERS", root_path %></h2>
		<div class="col-md-12 center btn-group-lg">
			<%= link_to "New Article", new_article_path, class: "btn btn-success"  if user_signed_in? %>
		</div>
		<div class="col-md-12 tags">
			<%= render "layouts/tags_clouds" %>
		</div>

		<div class="col-md-12 contact-info">
			<ul>
				<li><a href="#">Github</a></li>
				<li><a href="#">LinkedIn</a></li>
				<li><a href="#">Twitter</a></li>
			</ul>
		</div>

	</aside>
</div>

app/views/layouts/_tags_clouds.html.erb
<% tag_cloud(tags, %w(css1 css2 css3 css4)) do |tag, css_class| %>
  <%= link_to tag.name, tag_path(tag.name), :class => css_class %>
<% end %>

app/views/layouts/_top_menu.html.erb
<div class="user-mini-controls">
	<ul>
		<% if user_signed_in? %>
			<li><%= link_to current_user.name, profile_path(current_user) %> | </li>
			<li><%= link_to "sign out", signout_path %></li>
		<% else %>
			<li><%= link_to "sign in" , signin_path %></li>
		<% end %>
	</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Codebloggers</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="col-md-12 container">
	<%= render "layouts/header" %>

	<div class="col-md-9 main-body">

		<%= render "layouts/top_menu" %>

		<%= render "layouts/flash_messages" %>

		<%= yield %>
	</div>
</div>


<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES * * */
    var disqus_shortname = 'codebloggers';
    
    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function () {
        var s = document.createElement('script'); s.async = true;
        s.type = 'text/javascript';
        s.src = '//' + disqus_shortname + '.disqus.com/count.js';
        (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
    }());
</script>

</body>
</html>